// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantKeeperAPI.Database;

#nullable disable

namespace PlantKeeperAPI.Database.Migrations
{
    [DbContext(typeof(PlantKeeperDbContext))]
    [Migration("20251103013937_RepottingFertilizationAndObservationLog")]
    partial class RepottingFertilizationAndObservationLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PlantKeeperAPI.Entities.FertilizationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FertilizationMethodId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FertilizationMethodId");

                    b.HasIndex("PlantId");

                    b.ToTable("FertilizationLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.FertilizationMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("FertilizationMethods");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Lighting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Lighting");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.ObservationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("ObservationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("ObservationLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HumidityConditions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("LightingTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameInEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("SoilTypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LightingTypeId");

                    b.HasIndex("SoilTypeId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.RepottingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("RepottingLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Soil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Soil");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("KeeperId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WateringMethodId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("WateringMethodId");

                    b.ToTable("WateringLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("WateringMethods");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.FertilizationLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.FertilizationMethod", "FertilizationMethod")
                        .WithMany("FertilizationLogs")
                        .HasForeignKey("FertilizationMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("FertilizationLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FertilizationMethod");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.ObservationLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("ObservationLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Plant", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Lighting", "LightingType")
                        .WithMany("Plants")
                        .HasForeignKey("LightingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Soil", "SoilType")
                        .WithMany("Plants")
                        .HasForeignKey("SoilTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LightingType");

                    b.Navigation("SoilType");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.RepottingLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("RepottingLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("WateringLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.WateringMethod", "WateringMethod")
                        .WithMany("WateringLogs")
                        .HasForeignKey("WateringMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("WateringMethod");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.FertilizationMethod", b =>
                {
                    b.Navigation("FertilizationLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Lighting", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Plant", b =>
                {
                    b.Navigation("FertilizationLogs");

                    b.Navigation("ObservationLogs");

                    b.Navigation("RepottingLogs");

                    b.Navigation("WateringLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Soil", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringMethod", b =>
                {
                    b.Navigation("WateringLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
