// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantKeeperAPI.Database;

#nullable disable

namespace PlantKeeperAPI.Database.Migrations
{
    [DbContext(typeof(PlantKeeperDbContext))]
    partial class PlantKeeperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeneficialOrganismPest", b =>
                {
                    b.Property<Guid>("ControlledById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PestsControlledId")
                        .HasColumnType("uuid");

                    b.HasKey("ControlledById", "PestsControlledId");

                    b.HasIndex("PestsControlledId");

                    b.ToTable("BeneficialOrganismPests", (string)null);
                });

            modelBuilder.Entity("BeneficialOrganismPlantSpecies", b =>
                {
                    b.Property<Guid>("BeneficialOrganismsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupportingSpeciesId")
                        .HasColumnType("uuid");

                    b.HasKey("BeneficialOrganismsId", "SupportingSpeciesId");

                    b.HasIndex("SupportingSpeciesId");

                    b.ToTable("SpeciesBeneficialOrganisms", (string)null);
                });

            modelBuilder.Entity("PestTreatment", b =>
                {
                    b.Property<Guid>("PestsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreatmentsId")
                        .HasColumnType("uuid");

                    b.HasKey("PestsId", "TreatmentsId");

                    b.HasIndex("TreatmentsId");

                    b.ToTable("PestTreatments", (string)null);
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.BeneficialOrganism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SuggestedPlants")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("BeneficialOrganisms");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Climate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Humidity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Precipitation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sun")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Wind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Climates");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.FertilizationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dose")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FertilizerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FertilizerId");

                    b.HasIndex("PlantId");

                    b.ToTable("FertilizationLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Fertilizer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NpkRatio")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.ToTable("Fertilizers");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.GrowthLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.Property<decimal?>("HeightToLastNodeCm")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("GrowthLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.ObservationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("ObservationLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Pest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Pests");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PlantSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClimateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FertilizationFrequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FertilizationNotes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FloweringHabit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameInEnglish")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PottingMixId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClimateId");

                    b.HasIndex("PottingMixId");

                    b.ToTable("PlantSpecies");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PottingMix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("PottingMixes");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PropagationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("PropagationMethodId")
                        .HasColumnType("uuid");

                    b.Property<string>("RootingHormone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("SourcePlantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TargetTransplantWindow")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PropagationMethodId");

                    b.HasIndex("SourcePlantId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("PropagationBatches");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PropagationMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("PropagationMethods");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.RepottingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("RepottingLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesCareProfile", b =>
                {
                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<string>("LightMax")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LightMin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LightNotes")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaxTemperatureCelsius")
                        .HasColumnType("integer");

                    b.Property<int>("MinTemperatureCelsius")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoilPhMax")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<decimal>("SoilPhMin")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<string>("SoilPhNotes")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WateringRequirement")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("WindTolerance")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("WindToleranceNotes")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SpeciesId");

                    b.ToTable("SpeciesCareProfiles");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesFertilizerRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Suitability")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId", "Category")
                        .IsUnique();

                    b.ToTable("SpeciesFertilizerRecommendations");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesFloweringProfile", b =>
                {
                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<string>("BloomCareNotes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BloomSeason")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SeedHarvestTiming")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SeedViability")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SpeciesId");

                    b.ToTable("SpeciesFloweringProfiles");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesPropagationMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BestSeason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PropagationMethodId")
                        .HasColumnType("uuid");

                    b.Property<string>("RootingHormone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropagationMethodId");

                    b.HasIndex("SpeciesId", "PropagationMethodId")
                        .IsUnique();

                    b.ToTable("SpeciesPropagationMethods");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesToxicityProfile", b =>
                {
                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToHumans")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ToHumansNotes")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ToPets")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ToPetsNotes")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("SpeciesId");

                    b.ToTable("SpeciesToxicityProfiles");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesTreatmentRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Safety")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentId");

                    b.HasIndex("SpeciesId", "TreatmentId")
                        .IsUnique();

                    b.ToTable("SpeciesTreatmentRecommendations");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Treatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.TreatmentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("TreatmentLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.HasIndex("PlantId");

                    b.ToTable("WateringLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("WateringMethods");
                });

            modelBuilder.Entity("BeneficialOrganismPest", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.BeneficialOrganism", null)
                        .WithMany()
                        .HasForeignKey("ControlledById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Pest", null)
                        .WithMany()
                        .HasForeignKey("PestsControlledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeneficialOrganismPlantSpecies", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.BeneficialOrganism", null)
                        .WithMany()
                        .HasForeignKey("BeneficialOrganismsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.PlantSpecies", null)
                        .WithMany()
                        .HasForeignKey("SupportingSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PestTreatment", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Pest", null)
                        .WithMany()
                        .HasForeignKey("PestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Treatment", null)
                        .WithMany()
                        .HasForeignKey("TreatmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.FertilizationLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Fertilizer", "FertilizerUsed")
                        .WithMany("Logs")
                        .HasForeignKey("FertilizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("FertilizationLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FertilizerUsed");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.GrowthLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("GrowthLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.ObservationLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("ObservationLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Plant", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.PlantSpecies", "Species")
                        .WithMany("Plants")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PlantSpecies", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Climate", "Climate")
                        .WithMany("SpeciesList")
                        .HasForeignKey("ClimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.PottingMix", "PottingMix")
                        .WithMany("SpeciesList")
                        .HasForeignKey("PottingMixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Climate");

                    b.Navigation("PottingMix");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PropagationBatch", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.PropagationMethod", "Method")
                        .WithMany("Batches")
                        .HasForeignKey("PropagationMethodId");

                    b.HasOne("PlantKeeperAPI.Entities.Plant", "SourcePlant")
                        .WithMany("PropagationBatches")
                        .HasForeignKey("SourcePlantId");

                    b.HasOne("PlantKeeperAPI.Entities.PlantSpecies", "Species")
                        .WithMany("PropagationBatches")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("SourcePlant");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.RepottingLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("RepottingLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesCareProfile", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.PlantSpecies", "Species")
                        .WithOne("Care")
                        .HasForeignKey("PlantKeeperAPI.Entities.SpeciesCareProfile", "SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesFertilizerRecommendation", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.PlantSpecies", "Species")
                        .WithMany("FertilizerRecommendations")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesFloweringProfile", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.PlantSpecies", "Species")
                        .WithOne("Flowering")
                        .HasForeignKey("PlantKeeperAPI.Entities.SpeciesFloweringProfile", "SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesPropagationMethod", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.PropagationMethod", "Method")
                        .WithMany("SpeciesLinks")
                        .HasForeignKey("PropagationMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.PlantSpecies", "Species")
                        .WithMany("PropagationMethods")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesToxicityProfile", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.PlantSpecies", "Species")
                        .WithOne("Toxicity")
                        .HasForeignKey("PlantKeeperAPI.Entities.SpeciesToxicityProfile", "SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.SpeciesTreatmentRecommendation", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.PlantSpecies", "Species")
                        .WithMany("TreatmentRecommendations")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Treatment", "Treatment")
                        .WithMany("SpeciesRecommendations")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.TreatmentLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("TreatmentLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Treatment", "Treatment")
                        .WithMany("Logs")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.WateringMethod", "WateringMethod")
                        .WithMany("Logs")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("WateringLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("WateringMethod");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Climate", b =>
                {
                    b.Navigation("SpeciesList");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Fertilizer", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Plant", b =>
                {
                    b.Navigation("FertilizationLogs");

                    b.Navigation("GrowthLogs");

                    b.Navigation("ObservationLogs");

                    b.Navigation("PropagationBatches");

                    b.Navigation("RepottingLogs");

                    b.Navigation("TreatmentLogs");

                    b.Navigation("WateringLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PlantSpecies", b =>
                {
                    b.Navigation("Care")
                        .IsRequired();

                    b.Navigation("FertilizerRecommendations");

                    b.Navigation("Flowering");

                    b.Navigation("Plants");

                    b.Navigation("PropagationBatches");

                    b.Navigation("PropagationMethods");

                    b.Navigation("Toxicity")
                        .IsRequired();

                    b.Navigation("TreatmentRecommendations");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PottingMix", b =>
                {
                    b.Navigation("SpeciesList");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PropagationMethod", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("SpeciesLinks");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Treatment", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("SpeciesRecommendations");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringMethod", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
