// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantKeeperAPI.Database;

#nullable disable

namespace PlantKeeperAPI.Database.Migrations
{
    [DbContext(typeof(PlantKeeperDbContext))]
    partial class PlantKeeperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PlantKeeperAPI.Entities.Climate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Humidity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Precipitation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sun")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Wind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Climates");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.FertilizationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.HasIndex("PlantId");

                    b.ToTable("FertilizationLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.FertilizationMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("FertilizationMethods");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.ObservationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("ObservationLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PlantSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClimateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameInSpanish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("PottingMixId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClimateId");

                    b.HasIndex("PottingMixId");

                    b.ToTable("PlantSpecies");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PottingMix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("PottingMixes");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.RepottingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("RepottingLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.TreatmentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.HasIndex("PlantId");

                    b.ToTable("TreatmentLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.TreatmentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TreatmentMethods");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.HasIndex("PlantId");

                    b.ToTable("WateringLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("WateringMethods");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.FertilizationLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.FertilizationMethod", "FertilizationMethod")
                        .WithMany("Logs")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("FertilizationLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FertilizationMethod");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.ObservationLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("ObservationLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Plant", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.PlantSpecies", "Species")
                        .WithMany("Plants")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PlantSpecies", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Climate", "Climate")
                        .WithMany("SpeciesList")
                        .HasForeignKey("ClimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.PottingMix", "PottingMix")
                        .WithMany("SpeciesList")
                        .HasForeignKey("PottingMixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Climate");

                    b.Navigation("PottingMix");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.RepottingLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("RepottingLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.TreatmentLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.TreatmentMethod", "TreatmentMethod")
                        .WithMany("Logs")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("TreatmentLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("TreatmentMethod");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringLog", b =>
                {
                    b.HasOne("PlantKeeperAPI.Entities.WateringMethod", "WateringMethod")
                        .WithMany("Logs")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantKeeperAPI.Entities.Plant", "Plant")
                        .WithMany("WateringLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("WateringMethod");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Climate", b =>
                {
                    b.Navigation("SpeciesList");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.FertilizationMethod", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.Plant", b =>
                {
                    b.Navigation("FertilizationLogs");

                    b.Navigation("ObservationLogs");

                    b.Navigation("RepottingLogs");

                    b.Navigation("TreatmentLogs");

                    b.Navigation("WateringLogs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PlantSpecies", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.PottingMix", b =>
                {
                    b.Navigation("SpeciesList");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.TreatmentMethod", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("PlantKeeperAPI.Entities.WateringMethod", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
